-- كوكب كراكيب: مخطط Supabase لرحلة البيع المُدارة بواسطة مالك الموقع.
-- لا تستخدم هذه الجداول لإظهار بيانات العملاء للعامة؛ الواجهة العامة تعتمد على view آمن ودالة عداد فقط.
create extension if not exists "uuid-ossp";

create type public.account_role as enum ('client','trader','admin');
create type public.trader_status as enum ('pending','active','suspended','rejected');
create type public.sale_request_status as enum ('review','assigned','contacted','completed','rejected');

create table public.profiles (
  id uuid primary key references auth.users on delete cascade,
  role public.account_role not null default 'client',
  full_name text,
  phone text,
  city text,
  created_at timestamptz not null default now()
);

-- هذه البيانات هي الوحيدة التي يمكن عرضها في دليل التجار بعد اعتماد المالك.
create table public.trader_profiles (
  id uuid primary key references public.profiles(id) on delete cascade,
  display_name text not null,
  specialty text not null,
  service_city text not null,
  about text,
  rating numeric(2,1) not null default 0 check (rating >= 0 and rating <= 5),
  review_count integer not null default 0 check (review_count >= 0),
  status public.trader_status not null default 'pending',
  verified_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.sale_requests (
  id uuid primary key default uuid_generate_v4(),
  client_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  category text not null,
  description text,
  quantity numeric not null check(quantity > 0),
  unit text not null,
  location_text text not null,
  image_url text,
  status public.sale_request_status not null default 'review',
  assigned_trader_id uuid references public.trader_profiles(id),
  assigned_by uuid references public.profiles(id),
  assigned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint assignment_requires_trader check (
    (status in ('review','rejected') and assigned_trader_id is null)
    or (status in ('assigned','contacted','completed') and assigned_trader_id is not null)
  )
);
create index sale_requests_client_idx on public.sale_requests(client_id,created_at desc);
create index sale_requests_assigned_trader_idx on public.sale_requests(assigned_trader_id,created_at desc);

create table public.request_images (
  id bigint generated by default as identity primary key,
  sale_request_id uuid not null references public.sale_requests(id) on delete cascade,
  url text not null,
  sort_order int not null default 0
);

-- لا يُنشأ الحوار إلا في سياق طلب أُسند فعلًا لتاجر.
create table public.conversations (
  id uuid primary key default uuid_generate_v4(),
  sale_request_id uuid not null unique references public.sale_requests(id) on delete cascade,
  client_id uuid not null references public.profiles(id),
  trader_id uuid not null references public.trader_profiles(id),
  created_at timestamptz not null default now()
);
create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id),
  body text not null check(char_length(body) <= 2000),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.trader_reviews (
  id bigint generated by default as identity primary key,
  sale_request_id uuid not null unique references public.sale_requests(id) on delete cascade,
  reviewer_id uuid not null references public.profiles(id),
  trader_id uuid not null references public.trader_profiles(id),
  rating smallint not null check(rating between 1 and 5),
  body text,
  created_at timestamptz not null default now()
);

-- تحقق مركزي لصلاحيات لوحة المالك. عيّن role=admin فقط عبر خدمة خلفية موثوقة.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin')
$$;

-- يعيد الرقم فقط، لذلك يمكن عرضه علنًا من دون كشف أي سجل عميل أو اسم أو رقم هاتف.
create or replace function public.client_registration_count()
returns bigint language sql stable security definer set search_path = public as $$
  select count(*) from public.profiles where role = 'client'
$$;
grant execute on function public.client_registration_count() to anon, authenticated;

-- عرض عام محدود لطلبات البيع التي اعتمدها المالك وأُسندت بالفعل.
-- لا يحتوي client_id أو أي بيانات تعريفية للعميل.
create view public.sale_opportunities as
select
  r.id, r.title, r.category, r.description, r.quantity, r.unit, r.location_text,
  r.image_url, r.status, r.created_at,
  t.id as trader_id, t.display_name as trader_name, t.specialty as trader_specialty,
  t.service_city as trader_city, t.rating as trader_rating, t.review_count as trader_review_count
from public.sale_requests r
join public.trader_profiles t on t.id = r.assigned_trader_id
where r.status in ('assigned','contacted','completed') and t.status = 'active';
grant select on public.sale_opportunities to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.trader_profiles enable row level security;
alter table public.sale_requests enable row level security;
alter table public.request_images enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.trader_reviews enable row level security;

-- ملف العميل خاص؛ يستطيع المالك فقط الاطلاع على البيانات التشغيلية عند الحاجة، ولا توجد سياسة قراءة عامة.
create policy "profile owner reads own profile" on public.profiles for select using(id = auth.uid());
create policy "admin reads profiles" on public.profiles for select using(public.is_admin());
create policy "profile owner updates own profile" on public.profiles for update using(id = auth.uid()) with check(id = auth.uid() and role <> 'admin');

-- يقرأ الجميع بطاقة التاجر العامة فقط من هذا الجدول، ولا توجد به بيانات اتصال خاصة.
create policy "public reads active traders" on public.trader_profiles for select using(status = 'active' or id = auth.uid() or public.is_admin());
create policy "trader creates own public profile" on public.trader_profiles for insert with check(id = auth.uid());
create policy "trader updates pending profile" on public.trader_profiles for update using(id = auth.uid() and status = 'pending') with check(id = auth.uid() and status = 'pending');
create policy "admin manages traders" on public.trader_profiles for all using(public.is_admin()) with check(public.is_admin());

-- العميل يقرأ طلباته فقط، والتاجر لا يرى إلا الطلبات المسندة إليه، والمالك يرى جميع الطلبات.
create policy "client creates own sale request" on public.sale_requests for insert with check(client_id = auth.uid() and status = 'review' and assigned_trader_id is null);
create policy "client reads own sale requests" on public.sale_requests for select using(client_id = auth.uid());
create policy "trader reads assigned requests" on public.sale_requests for select using(assigned_trader_id = auth.uid());
create policy "admin reads all requests" on public.sale_requests for select using(public.is_admin());
create policy "admin assigns requests" on public.sale_requests for update using(public.is_admin()) with check(public.is_admin());

create policy "request participants read images" on public.request_images for select using(exists(select 1 from public.sale_requests r where r.id = sale_request_id and (r.client_id = auth.uid() or r.assigned_trader_id = auth.uid() or public.is_admin())));
create policy "client uploads own request images" on public.request_images for insert with check(exists(select 1 from public.sale_requests r where r.id = sale_request_id and r.client_id = auth.uid()));

create policy "participants read conversations" on public.conversations for select using(auth.uid() in(client_id,trader_id) or public.is_admin());
create policy "participants read messages" on public.messages for select using(exists(select 1 from public.conversations c where c.id = conversation_id and (auth.uid() in(c.client_id,c.trader_id) or public.is_admin())));
create policy "participants send messages" on public.messages for insert with check(sender_id = auth.uid() and exists(select 1 from public.conversations c where c.id = conversation_id and auth.uid() in(c.client_id,c.trader_id)));

create policy "public reads trader reviews" on public.trader_reviews for select using(true);
create policy "client reviews completed assigned request" on public.trader_reviews for insert with check(reviewer_id = auth.uid() and exists(select 1 from public.sale_requests r where r.id = sale_request_id and r.client_id = auth.uid() and r.assigned_trader_id = trader_id and r.status = 'completed'));

-- نفّذ عبر Edge Function / service role: اعتماد التاجر، إسناد الطلب، إنشاء المحادثة وتحديث متوسط التقييم.
-- لا تمنح role=admin أو صلاحية الإسناد مباشرة من واجهة المتصفح.
